"""Reporter agent — generates structured investigation reports."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import anthropic

from sherlock.config import settings
from sherlock.models import Investigation


REPORTER_SYSTEM = """You are a report writer for an AI investigation agent called Sherlock.
Given an investigation's findings, produce a clear, well-structured Markdown report.

Report structure:
# Investigation: {query}

## Executive Summary
2-3 sentence overview of key findings.

## Key Findings
Numbered findings with confidence indicators [HIGH/MEDIUM/LOW].

## Evidence & Sources
Cite every source URL. Group by finding.

## Gaps & Limitations
What couldn't be determined. What needs further investigation.

## Methodology
Brief description of how the investigation was conducted.

---
*Generated by Sherlock Holmes AI on {date}*

RULES:
- Every claim must reference a source
- Be direct and factual — no filler
- Flag low-confidence findings explicitly
- Include source URLs as clickable markdown links"""


async def generate_report(investigation: Investigation) -> str:
    """Generate a markdown investigation report from findings."""
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    findings_text = ""
    for i, finding in enumerate(investigation.findings, 1):
        sources = "\n".join(
            f"  - [{e.source_title or 'Source'}]({e.source_url})"
            for e in finding.evidence
            if e.source_url
        )
        findings_text += (
            f"\n### Finding {i} [{finding.confidence.value.upper()}]\n"
            f"{finding.claim}\n"
            f"Sources:\n{sources}\n"
        )

    response = await client.messages.create(
        model=settings.model,
        max_tokens=settings.max_tokens,
        system=REPORTER_SYSTEM,
        messages=[
            {
                "role": "user",
                "content": (
                    f"Investigation query: {investigation.query}\n"
                    f"Type: {investigation.investigation_type.value}\n"
                    f"Sub-tasks completed: {len([t for t in investigation.sub_tasks if t.status == 'completed'])}/{len(investigation.sub_tasks)}\n\n"
                    f"Findings:\n{findings_text}\n\n"
                    "Generate the full investigation report in Markdown."
                ),
            }
        ],
    )

    return response.content[0].text


async def save_report(investigation: Investigation, markdown: str) -> Path:
    """Save a report to the outputs directory."""
    settings.ensure_dirs()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    slug = investigation.query[:50].lower().replace(" ", "_").replace("/", "_")
    filename = f"{timestamp}_{slug}.md"
    path = settings.output_dir / filename

    path.write_text(markdown, encoding="utf-8")
    return path
